name: brianbeatty
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6441770824603736
title: Brian Beatty
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03030d'
    - '#61403f'
    - '#f8c55d'
    - '#a42214'
    - '#aa754a'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.7369116365443915
  rhythmicContrast: 0.75
purpose: []
